# Generated by Django 6.0.1 on 2026-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
