# Generated by Django 6.0.1 on 2026-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_fileitem_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
