# Generated by Django 6.0.1 on 2026-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kullanıcı Klasörü'),
        ),
    ]
